# Generated by Django 4.2.4 on 2023-08-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='body',
        ),
        migrations.AddField(
            model_name='about',
            name='body1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='body2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='body3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
