# Generated by Django 4.2.4 on 2023-08-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_remove_service_image_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='alt',
        ),
    ]
