# Generated by Django 4.2.4 on 2023-09-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_remove_service_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='sort',
            field=models.CharField(choices=[('design', 'Design'), ('marketing', 'Marketing'), ('development', 'Development')], default='design', max_length=300),
        ),
    ]
