# Generated by Django 4.2.4 on 2023-09-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_portfolio_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('canonical', models.CharField(max_length=500)),
                ('locale', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('descriptionOg', models.CharField(max_length=500)),
                ('site_name', models.CharField(max_length=500)),
                ('modified_time', models.CharField(max_length=500)),
            ],
        ),
    ]
