# Generated by Django 4.2.4 on 2023-09-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_alter_tags_canonical_alter_tags_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facts',
            options={'verbose_name': 'Fact', 'verbose_name_plural': 'Facts'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Home Page Tag', 'verbose_name_plural': 'Home Page Tags'},
        ),
    ]
