# Generated by Django 4.2.4 on 2023-09-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_alter_facts_options_alter_tags_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='canonical',
        ),
    ]
