# Generated by Django 4.2.4 on 2023-09-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_remove_tags_canonical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='site_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
