# Generated by Django 4.2.4 on 2023-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_delete_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('locale', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('descriptionOg', models.CharField(blank=True, max_length=500, null=True)),
                ('site_name', models.CharField(blank=True, max_length=400, null=True)),
                ('modified_time', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Home Page Tag',
                'verbose_name_plural': 'Home Page Tags',
            },
        ),
    ]
