# Generated by Django 4.2.4 on 2023-08-30 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 10, 34, 25, 636131)),
        ),
    ]
