# Generated by Django 4.2.4 on 2023-08-30 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_email_message_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 10, 36, 45, 717860)),
        ),
    ]
