# Generated by Django 4.2.4 on 2023-09-01 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_canonical_article_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='modified_time',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 20, 23, 12, 219350)),
        ),
    ]
