# Generated by Django 4.2.4 on 2023-09-01 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_article_modified_time_alter_article_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('canonical', models.CharField(blank=True, max_length=500, null=True)),
                ('locale', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('descriptionOg', models.CharField(blank=True, max_length=500, null=True)),
                ('site_name', models.CharField(blank=True, max_length=500, null=True)),
                ('modified_time', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 21, 13, 8, 217882)),
        ),
    ]
