# Generated by Django 4.2.4 on 2023-09-01 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_tags_canonical_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Blog Page Tag', 'verbose_name_plural': 'Blog Page Tags'},
        ),
        migrations.AddField(
            model_name='tags',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 21, 26, 45, 234892)),
        ),
    ]
