# Generated by Django 4.2.4 on 2023-09-01 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_tags_options_tags_height_tags_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 22, 22, 28, 304817)),
        ),
    ]
