# Generated by Django 4.2.4 on 2023-09-01 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_tags_pagetitle_alter_article_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='pagetitle',
        ),
        migrations.AddField(
            model_name='article',
            name='pagetitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 23, 37, 51, 457811)),
        ),
    ]
